### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by sisou** [nimiq/wallet#8]
Add a dark mode theme to the app.

**Comment by Saiv46** [comment]
I inverted color pallete and it looks dope

![Screenshot](https://user-images.githubusercontent.com/47699394/196119664-74f90dac-5bee-4f9e-aead-8a3b158586b7.png)

```css
:root {
  --nimiq-blue: #fff;
  --nimiq-light-blue: #35b2fa;
  --nimiq-gold: #ecb516;
  --nimiq-green: #43dec7;
  --nimiq-orange: #fd8803;
  --nimiq-red: #cd3826;
  --nimiq-purple: #8874b4;
  --nimiq-pink: #970f05;
  --nimiq-light-green: #8cb44f;
  --nimiq-brown: #b79386;
  --nimiq-gray: #0b0b0b;
  --nimiq-light-gray: #050505;
  --nimiq-white: #000;
  --nimiq-light-blue-on-dark: #19bf3;
  --nimiq-red-on-dark: #b71400;
  --nimiq-blue-darkened: #cccfea;
  --nimiq-light-blue-darkened: #3cadff;
  --nimiq-gold-darkened: #edaa1a;
  --nimiq-green-darkened: #4ddfcb;
  --nimiq-orange-darkened: #ff7803;
  --nimiq-red-darkened: #cf2e2e;
  --text-100: #fff;
  --text-80: rgba(255,255,255,.8);
  --text-70: rgba(255,255,255,.7);
  --text-60: rgba(255,255,255,.6);
  --text-50: rgba(255,255,255,.5);
  --text-40: rgba(255,255,255,.4);
  --text-35: rgba(255,255,255,.35);
  --text-30: rgba(255,255,255,.3);
  --text-25: rgba(255,255,255,.25);
  --text-22: rgba(255,255,255,.22);
  --text-20: rgba(255,255,255,.2);
  --text-16: rgba(255,255,255,.16);
  --text-14: rgba(255,255,255,.14);
  --text-12: rgba(255,255,255,.12);
  --text-10: rgba(255,255,255,.1);
  --text-6: rgba(255,255,255,.06);
}

#app .sidebar {
  background: var(--nimiq-white);
}

.receive.nq-button-s.flex-row {
  background-color: var(--nimiq-light-green);
}

```
